spring.application.name=Clinic
# Database URL (replace 'localhost:5432' and 'your_db_name' with your details)
spring.datasource.url=jdbc:postgresql://localhost:5432/Clinic_db
spring.datasource.username=postgres
spring.datasource.password=ADMIN123

# Database Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings (Optional, for auto-generating tables)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Server Configuration (Example for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huzaifa0646@gmail.com
spring.mail.password=pruw bhmu duky ehfs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: To see logs in the console to verify emails are sending
spring.mail.properties.mail.debug=true
